import "oaidl.idl";
import "ocidl.idl";

[
	uuid(06A9926D-505D-42A9-8421-D0AEA39AABDE),
	version(1.0),
]
library UVCPluginLib
{
	importlib("stdole2.tlb");
};

// IExtensionUnit interface
import "unknwn.idl";
[
	object,
	local,
	uuid(8C5589ED-5EDE-488C-58A7-34C40D747AEA),
	pointer_default(unique)
]
interface IExtensionUnit : IUnknown
{
	HRESULT get_InfoSize(
		[out] ULONG *pulSize);
	HRESULT get_Info(
		[in] ULONG ulSize,
		[in, out, size_is(ulSize)] BYTE pInfo[]);
	HRESULT get_PropertySize(
		[in] ULONG PropertyId,
		[out] ULONG *pulSize);
	HRESULT get_Property(
		[in] ULONG PropertyId,
		[in] ULONG ulSize,
		[in, out, size_is(ulSize)] BYTE pValue[]);
	HRESULT put_Property(
		[in] ULONG PropertyId,
		[in] ULONG ulSize,
		[in, out, size_is(ulSize)] BYTE pValue[]);
	HRESULT get_PropertyRange(
		[in] ULONG PropertyId,
		[in] ULONG ulSize,
		[in, out, size_is(ulSize)] BYTE pMin[],
		[in, out, size_is(ulSize)] BYTE pMax[],
		[in, out, size_is(ulSize)] BYTE pSteppingDelta[],
		[in, out, size_is(ulSize)] BYTE pDefault[]);
};

